const actions = {
  PUT_LIST_MOVIES: "PUT_LIST_MOVIES",
  PUT_FULL_INFO_MOVIE: "PUT_FULL_INFO_MOVIE",
  CHANGE_ORDER_SORT: "CHANGE_ORDER_SORT",
  INCREMENT_COUNT_PAGE: "INCREMENT_COUNT_PAGE",
  RESETTING_COUNT_PAGE: "RESETTING_COUNT_PAGE",
};

export default actions;
